
service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: dev
  region: us-east-1
  environment:
    foo: 123
  apiGateway:
    shouldStartNameWithService: true

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors:
            origin: '*'
            methods: 'GET'
            headers:
              - Content-Type
              - cb-access-key
              - cb-access-sign
              - cb-access-timestamp
              - cb-access-passphrase
              - x-mbx-apikey
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
      - http:
          path: ''
          method: post
          cors: true